name: Build Executables

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - run: pyinstaller --onefile Aperio.py --name Aperio

      - uses: actions/upload-artifact@v4
        with:
          name: Aperio-${{ matrix.os }}
          path: dist/Aperio*
