name: Build Executables

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - run: pip install -r requirements.txt pyinstaller

      - run: pyinstaller --onefile main.py --name Aperio

      - if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Aperio-windows
          path: dist/Aperio.exe

      - if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Aperio-linux
          path: dist/Aperio

      - if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Aperio-macos
          path: dist/Aperio
